### ISSUE TITLE
Unused Link/handleLinkClick?

### ISSUE THREAD

**Issue by framp** [developit/preact-router#146]
The readme says that a tags are automatically wired.
How is that supposed to happen? Through the exported Link which should be manually used by the user in place of the a tag?
I can't find any other place where the automatic wiring is happening.

The exported Link is also not being used in the real example: http://jsfiddle.net/developit/qc73v9va/
handleLinkClick is never called

If that's the case, I'd suggest to just update documentation accordingly or remove the Link export

**Comment by developit** [comment]
`<Link />` uses manual wiring, whereas `<a>` is automatically hooked via event delegation.  You're right though, they are duplicative. That's because the automatic wiring of `<a>` was only added in the most recent version. Part of the reason `<Link>` is still around is for backwards compatibility, and the other part is because there's talk of making the auto-wiring of `<a>` a configuration option, which would then necessitate a `<Link>` component to do that wiring.

**Comment by framp** [comment]
Oh, my bad, I must have missed the delegateLinkHandler function https://github.com/developit/preact-router/blob/master/src/index.js#L111
Thanks for the answer.

On a slightly related note, do you think it would be appropriate to add a handler for form submits as well?
Happy to work on a PR if that's the case.
(The end result being something close to: https://github.com/insin/react-router-form)

**Comment by developit** [comment]
Hmm - definitely an interesting idea, just not sure how it'd work with `preact-router`.  Hit me up on the [Preact Slack](https://preact-slack.now.sh) if you want to chat about it!
