### ISSUE TITLE
Can this be used for SSR?

### ISSUE THREAD

**Issue by lucas-aragno** [developit/preact-router#207]
I've built a SSR preact app that works just fine, I'm trying to add the routing now but doesn't seems to work, can this be achieved using this module? I haven't found any boilerplate using preact for ssr with any router

**Comment by developit** [comment]
I usually have my `<App>` component (the root component) accept a `url` prop, which it passes to `<Router>`:

```js
const App = ({ url }) => (
  <Router url={url}>
    <Home path="/" />
    <Foo path="/foo" />
    <NotFound default />
  </Router>
);
```

With that in place you can do this:

```js
import express from 'express';
import { h } from 'preact';
import renderToString from 'preact-render-to-string';
import App from '../client/components/app';

let server = express();
server.get('*', (req, res) => {
    let html = renderToString(
      <App url={req.url} />
    );
    res.text(`<!doctype html><html><body>${html}</body></html>`);
});
```

Let me know if that helps!

**Comment by lucas-aragno** [comment]
Thank you @developit actually I figure that out checking my old react ssr repos :man_facepalming: I'm closing the issue now thank you!

**Comment by brunoscopelliti** [comment]
@developit Thanks for your time here; it is very much appreciated.

Ok, so preact-router supports ssr of the app html.
I've a project, in which I'm using redux (with preact-redux) and I want to prepare on the server also the landing model.

I'm trying to replicate what people at react-training illustrate in this [tutorial](https://reacttraining.com/react-router/web/guides/server-rendering/data-loading).

I've a list of routes:

```
const routes = [
  { path: '/A',
    component: Root,
    loadData: () => getSomeData(),
  },
  { path: '/B/:id',
    component: Root,
    loadData: (params) => getDataById(params.id),
  },
  // etc.
]
```

and the `currentUrl`.

I've encountered a couple of problems.

1. How I can determine the matching route?
  I've opened a different [issue](https://github.com/developit/preact-router/issues/220) early this week with question... and currently I've implemented the work around mentioned in my follow up comment.

2. How I can get the value of matching parameter after I've determined the matching route. What I need is already implemented into `exec` method, but it is not exported. 
  Do you think it could be a good idea to export the `exec` method - maybe under a (more explicative & less RegExp-influenced) name -, so that it can be publicly accessed?

**Comment by developit** [comment]
I've replied to your other issue.

**Comment by DoMiNeLa10** [comment]
It would be nice to mention that SSR is supported, and that `url` prop can be passed to `Router` in order to save potential users the trouble of searching for this issue.

**Comment by MarcWeber** [comment]
I agree it's a documentation issue. Even referencing this issue would be enough _ssr supported_ done.

**Comment by derappelt** [comment]
> I usually have my `<App>` component (the root component) accept a `url` prop, which it passes to `<Router>`:
> 
> ```js
> const App = ({ url }) => (
>   <Router url={url}>
>     <Home path="/" />
>     <Foo path="/foo" />
>     <NotFound default />
>   </Router>
> );
> ```
> 
> With that in place you can do this:
> 
> ```js
> import express from 'express';
> import { h } from 'preact';
> import renderToString from 'preact-render-to-string';
> import App from '../client/components/app';
> 
> let server = express();
> server.get('*', (req, res) => {
>     let html = renderToString(
>       <App url={req.url} />
>     );
>     res.text(`<!doctype html><html><body>${html}</body></html>`);
> });
> ```
> 
> Let me know if that helps!

Works perfectly fine. Is there something equivalent for the Link tags?

```tsx
import Router from "preact-router";
import { Link } from "preact-router/match";
import Clock from "./Clock";

type AppProps = {
  url?: string;
};

export default ({ url }: AppProps) => (
  <div>
    <nav>
      <Link activeClassName="active" href="/">
        Home
      </Link>
      <Link activeClassName="active" href="/clock">
        Clock
      </Link>
    </nav>
    <Router url={url}>
      <div path="/">Home Page</div>
      <Clock path="/clock" />
    </Router>
  </div>
);
```
The "active" class is not set on ssr response not on hydrate. It's only set on clientside request.
