### ISSUE TITLE
Integration with preact-cycle

### ISSUE THREAD

**Issue by tompiarulli** [developit/preact-router#251]
I'm using [preact-cycle](https://github.com/developit/preact-cycle) in my project and I generally prefer using actions (mutations) instead of including links with explicit strings, for example:

```js
const DocumentButton = (props, {mutation}) => (
 <div onClick={mutation(SELECT_DOCUMENT)}>Document Name</div>
)

const SELECT_DOCUMENT = (state, id) => {
 route(`/documents/${id}`)
}
```

This works but I get strange behaviors (css layout breaking, console errors stating that the history stack can't push the same entry, etc.)

Is there a way to integrate preact-router and preact-cycle such that I can manage the url within my store and control url changes via mutations?

**Comment by developit** [comment]
It'd be quite difficult since `window.history` is a source of external state with its own lifecycle.  For example, you may wish to route to a given URL in your internal state representation, but should the browser push that as an entry into history, or update the URL in-place?

If you're looking to decouple entirely from browser history, you can use memory history:

```
import { createMemoryHistory } from 'history';

let history = createMemoryHistory();

<Router history={history}>
  etc
</Router>
```
