### ISSUE TITLE
How to default to a login form?

### ISSUE THREAD

**Issue by donadley** [developit/preact-router#28]
I am using browserify to add a series of forms to UI, but I am unable to navigate to the initial Login form. I am using the following and expecting the default Login component to display. Is this the intended function of the example code?
```
<Router>
  <A path="/" />
  <B path="/b" id="42" />
  <C path="/c/:id" />
  <D default />
</Router>
```
Below is what I tried:
```
import { h, render, Component } from 'preact';
import Router from 'preact-router';

const routes = () =>
	(
		<Router>
	      <Login default />
  		</Router>
	);

render(
	<routes />, placeholder
);
```

**Comment by developit** [comment]
Hi @donadley! The `default` prop is useful for things like "catch-all" or 404 pages, and your `<Login>` sounds like the former, so you're on the right track.

However, in your example, I notice you're using a lowercase name for `<routes>`.  The way JSX works means that will create a DOM element called `"routes"`, rather than actually rendering your `routes` component.  The best way I know of to illustrate this is by looking at Babel's output: https://goo.gl/qcHLXb

Switching the name to `<Routes>` in your example seems to work just like you described:
https://jsfiddle.net/developit/56jq2wzs/

![preview](https://i.gyazo.com/843e562adbaec84a35a938110d64769f.gif)

**Comment by developit** [comment]
Let me know if this solves your issue! :)

**Comment by donadley** [comment]
That did the trick and now I can move forward. Thank you for the help.
